def shared_pods
  pod 'BitmovinAdobeAnalytics', path: '../'
  pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.57.0'
  pod 'ACPCore', '~> 2.0'
  pod 'ACPAnalytics', '~> 2.0'
  pod 'ACPMedia', '~> 2.0'

  pod 'SwiftLint'
end

target 'BitmovinAdobeAnalytics_Example' do
  use_frameworks!
  platform :ios, '10.0'
  shared_pods

  pod 'GoogleAds-IMA-iOS-SDK', '3.12.1'
end

target 'BitmovinAdobeAnalytics_TvOSExample' do
  use_frameworks!
  platform :tvos, '10.0'

  shared_pods
end

target 'BitmovinAdobeAnalytics_Tests' do
  use_frameworks!
  platform :ios, '10.0'
  shared_pods

  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.1'
end
