source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
  pod 'BitmovinAdobeAnalytics', path: '../'
  pod 'BitmovinPlayer', '3.13.0'
  pod 'ACPCore', '~> 2.0'
  pod 'ACPAnalytics', '~> 2.0'
  pod 'ACPMedia', '~> 2.0'

  pod 'SwiftLint'
end

target 'BitmovinAdobeAnalytics_Example' do
  use_frameworks!
  platform :ios, '12.0'
  shared_pods

  pod 'GoogleAds-IMA-iOS-SDK', '3.14.5'
end

target 'BitmovinAdobeAnalytics_TvOSExample' do
  use_frameworks!
  platform :tvos, '12.0'

  shared_pods
end

target 'BitmovinAdobeAnalytics_Tests' do
  use_frameworks!
  platform :ios, '12.0'
  shared_pods

  pod 'Quick', '~> 4.0.0'
  pod 'Nimble', '~> 9.2.0'
end
